<?php

use rizalafani\fpdflaravel\Fpdf as FPDFS;
class PDF_MC_Table extends FPDFS{
    var $widths;
    var $aligns;
    
    function Footer(){
        $this->SetY(-9);
        $this->SetFont('Arial', '', 7);
        $this->SetFont('Arial', '', 7);
        $this->Cell(25, 4, 'Hal. : ' . $this->PageNo(), 0, 0, 'L');        
        $this->SetFont('Arial', 'I', 7);
        $this->Cell(175, 4, 'printed on : ' . date('d-m-Y H:i:s') . ' | Generated by Sipenmaru', 0, 1, 'R');
    }

    function SetWidths($w){
        $this->widths=$w;
    }

    function SetAligns($a){
        $this->aligns=$a;
    }

    function Row($data){
        $nb=0;
        for($i=0;$i<count($data);$i++)
            $nb=max($nb,$this->NbLines($this->widths[$i],$data[$i]));
        $h=8*$nb;
        //Issue a page break first if needed
        $this->CheckPageBreak($h);
        //Draw the cells of the row
        for($i=0;$i<count($data);$i++)
        {
            $w=$this->widths[$i];
            $a=isset($this->aligns[$i]) ? $this->aligns[$i] : 'L';
            //Save the current position
            $x=$this->GetX();
            $y=$this->GetY();
            //Draw the border
            $this->Rect($x,$y,$w,$h);
            //Print the text
            $this->MultiCell($w,8,$data[$i],0,$a);
            //Put the position to the right of the cell
            $this->SetXY($x+$w,$y);
        }
        //Go to the next line
        $this->Ln($h);
    }

    function RowNoLines($data){
        $nb=0;
        for($i=0;$i<count($data);$i++)
            $nb=max($nb,$this->NbLines($this->widths[$i],$data[$i]));
        $h=8*$nb;
        //Issue a page break first if needed
        $this->CheckPageBreak($h);
        //Draw the cells of the row
        for($i=0;$i<count($data);$i++)
        {
            $w=$this->widths[$i];
            $a=isset($this->aligns[$i]) ? $this->aligns[$i] : 'L';
            //Save the current position
            $x=$this->GetX();
            $y=$this->GetY();
            //Draw the border
//            $this->Rect($x,$y,$w,$h);
            //Print the text
            $this->MultiCell($w,8,$data[$i],0,$a);
            //Put the position to the right of the cell
            $this->SetXY($x+$w,$y);
        }
        //Go to the next line
        $this->Ln($h);
    }

    function CheckPageBreak($h){
        //If the height h would cause an overflow, add a new page immediately
        if($this->GetY()+$h>$this->PageBreakTrigger)
            $this->AddPage($this->CurOrientation);
    }

    function NbLines($w,$txt){
        //Computes the number of lines a MultiCell of width w will take
        $cw=&$this->CurrentFont['cw'];
        if($w==0)
            $w=$this->w-$this->rMargin-$this->x;
        $wmax=($w-2*$this->cMargin)*1000/$this->FontSize;
        $s=str_replace("\r",'',$txt);
        $nb=strlen($s);
        if($nb>0 and $s[$nb-1]=="\n")
            $nb--;
        $sep=-1;
        $i=0;
        $j=0;
        $l=0;
        $nl=1;
        while($i<$nb){
            $c=$s[$i];
            if($c=="\n"){
                $i++;
                $sep=-1;
                $j=$i;
                $l=0;
                $nl++;
                continue;
            }
            if($c==' ')
                $sep=$i;
            $l+=$cw[$c];
            if($l>$wmax){
                if($sep==-1){
                    if($i==$j)
                        $i++;
                }
                else
                    $i=$sep+1;
                $sep=-1;
                $j=$i;
                $l=0;
                $nl++;
            }
            else
                $i++;
        }
        return $nl;
    }
}

$pdf = new PDF_MC_Table('P', 'mm', array(210, 297));

$pdf->SetAutoPageBreak(true, 5);
$pdf->SetMargins(5, 8, 10);

//Halaman 1
$pdf->AddPage();
// Arial bold 15
$pdf->SetFont('Arial', 'BU', 14);
// Title
$pdf->Rect(5, 5, 200, 275, 'D');
$pdf->Cell(200, 12, 'CEK LIST BERKAS PERSYARATAN PENDAFTARAN PMDP', 0, 1, 'C');
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(160);
$pdf->Cell(40, 7, 'KODE PILIHAN :', 0, 1, 'C');
$pdf->Cell(160);
$pdf->Cell(40, 7, '71', 0, 1, 'C');

$pdf->SetFont('Arial', '',11);
$pdf->SetWidths(array(5,55,5,125));
$pdf->SetAligns(array('L','L','C','L'));
$pdf->RowNoLines(array('','NAMA',':','ALMAHYRA'));
$pdf->RowNoLines(array('','NO PENDAFTARAN',':','PMDP710002'));
$pdf->RowNoLines(array('','ASAL SEKOLAH',':','ALMAHYRA'));
$pdf->RowNoLines(array('','JURUSAN',':','PMDP710002'));
$pdf->RowNoLines(array('','ALAMAT RUMAH',':','PMDP710002'));
$pdf->RowNoLines(array('','TELP.',':','PMDP710002'));
$pdf->RowNoLines(array('','PILIHAN PRODI',':','PMDP710002'));

$pdf->Cell(5, 15, '', 0);
$pdf->Cell(95, 15, 'KELENGKAPAN BERKAS', 0, 0, 'L');
$pdf->Cell(95, 15, 'DIISI OLEH PANITIA', 0, 0, 'R');
$pdf->Cell(5, 15, '', 0, 1);

$pdf->Cell(5);
$pdf->Cell(10, 14, 'NO', 1, 0, 'C');
$pdf->Cell(125, 14, 'URAIAN', 1, 0, 'C');
$pdf->Cell(55, 7, 'KELANGKAPAN', 1, 1, 'C');
$pdf->Cell(140);
$pdf->Cell(27, 7, 'YA', 1, 0, 'C');
$pdf->Cell(28, 7, 'TIDAK', 1, 1, 'C');

$pdf->SetWidths(array(10,125,27,28));
$pdf->SetAligns(array('C','L','C','L'));
$pdf->Cell(5);
$pdf->Row(array('1','Formulir Rekomendasi Kepala Sekolah','',''));
$pdf->Cell(5);
$pdf->Row(array('2','Formulir Persetujuan Orang Tua / Wali','',''));
$pdf->Cell(5);
$pdf->Row(array('3','Kartu Pendaftaran Peserta Seleksi',':',''));
$pdf->Cell(5);
$pdf->Row(array('4','Formulir Konversi Nilai','',''));
$pdf->Cell(5);
$pdf->Row(array('5','Foto 4x6 3 lembar (1 lbr ditempel di formulir rekomendasi kepala sekolah dan 2 lbr ditempel dikartu seleksi)','',''));
$pdf->Cell(5);
$pdf->Row(array('6','Foto copy rapor dilegalisir.','',''));
$pdf->Cell(5);
$pdf->Row(array('7','Foto copy akreditasi sekolah dilegalisir','',''));
$pdf->Cell(5);
$pdf->Row(array('8','Foto copy sertifikat prestasi','',''));
$pdf->Cell(5);
$pdf->Row(array('9','Surat pernyataan','',''));
$pdf->Cell(5);
$pdf->Row(array('10','Surat Keterangan Sehat dari Dokter Pemerintah (RS, Puskesmas)','',''));
$pdf->Cell(5);
$pdf->Row(array('11','Slip/Bukti Setor Biaya Pendaftaran','',''));

$pdf->Cell(5, 7, '', 0, 1);
$pdf->Cell(5);
$pdf->Cell(125, 7, 'CATATAN:', 0, 0, 'L');
$pdf->Cell(65, 7, 'Semarang, 20 Januari 2017', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '....................................................................', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '....................................................................', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '....................................................................', 0, 0, 'L');
$pdf->Cell(65, 7, '.......................................', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '....................................................................', 0, 0, 'L');
$pdf->Cell(65, 7, 'PANITIA / PEMERIKSA', 0, 1, 'C');

$pdf->SetFont('Arial', 'I', 8);
$pdf->Cell(125, 17, '', 0, 1, 'L');
$pdf->Cell(5);
$pdf->Cell(125, 7, 'DIKIRIM KE PANITIA', 0, 1, 'L');


//Halaman 2
$pdf->AddPage();
// Arial bold 15
$pdf->SetFont('Arial', '', 12);
// Title
$pdf->Rect(5, 5, 200, 275, 'D');
$pdf->Cell(100, 7, '', 0, 0);
$pdf->Cell(95, 7, 'FM-POLTEKKES-SMG-BM-01-02/R0', 0, 1, 'R');
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(200, 12, 'NOMOR PENDAFTARAN: PMDP710002', 0, 1, 'C');
$pdf->SetFont('Arial', 'B', 14);
$pdf->Cell(200, 7, 'FORMULIR REKOMENDASI KEPALA SEKOLAH', 0, 1, 'C');
$pdf->Cell(200, 7, 'SELEKSI PENERIMAAN MAHASISWA BARU JALUR PMDP', 0, 1, 'C');
$pdf->Cell(200, 7, 'POLITEKNIK KESEHATAN SEMARANG', 0, 1, 'C');
$pdf->Cell(200, 7, 'TAHUN AKADEMIK 2017/2018', 0, 1, 'C');

$pdf->Cell(200, 14, '', 0, 1);
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(5, 7, '', 0, 0);
$pdf->Cell(90, 7, 'Kepada Yth.', 0, 0);
$pdf->Cell(60, 7, '', 0, 0, 'R');
$pdf->Cell(40, 50, '', 1, 0, 'C');
$pdf->Cell(5, 7, '', 0, 1, 'R');

$pdf->Cell(5, 7, '', 0, 0);
$pdf->Cell(90, 7, 'Direktur Politeknik Kesehatan Semarang', 0, 0);
$pdf->Cell(60, 7, '', 0, 0, 'R');
$pdf->Cell(40, 7, '', 0, 0, 'R');
$pdf->Cell(5, 7, '', 0, 1, 'R');

$pdf->Cell(5, 7, '', 0, 0);
$pdf->Cell(90, 7, 'di-', 0, 0);
$pdf->Cell(60, 7, '', 0, 0, 'R');
$pdf->Cell(40, 7, 'Pas foto', 0, 0, 'C');
$pdf->Cell(5, 7, '', 0, 1, 'R');

$pdf->Cell(10, 7, '', 0, 0);
$pdf->Cell(85, 7, 'SEMARANG', 0, 0);
$pdf->Cell(60, 7, '', 0, 0, 'R');
$pdf->Cell(40, 7, '4 x 6', 0, 0, 'C');
$pdf->Cell(5, 7, '', 0, 1, 'R');

$pdf->Cell(10, 22, '', 0, 0);
$pdf->Cell(85, 22, '', 0, 0);
$pdf->Cell(60, 22, '', 0, 0, 'R');
$pdf->Cell(40, 22, '(ditempel disini)', 0, 0, 'C');
$pdf->Cell(5, 22, '', 0, 1, 'R');

$pdf->SetFont('Arial', '',11);
$pdf->Cell(5);
$pdf->cell('190', 7, 'Yang bertandatangan di bawah ini, saya:', 0, 1, 'L');
$pdf->SetWidths(array(5,5,55,5,125));
$pdf->SetAligns(array('L','C','L','C','L'));
$pdf->RowNoLines(array('','1','Nama Kepala Sekolah',':','JUANDA'));
$pdf->RowNoLines(array('','2','Nama Sekolah',':','SMAN 1'));
$pdf->RowNoLines(array('','3','Jurusan',':','IPA'));
$pdf->RowNoLines(array('','4','Akreditasi Sekolah',':','A '));
$pdf->RowNoLines(array('','5','Alamat Sekolah',':','Semarang'));

$pdf->SetWidths(array(5,190,5));
$pdf->SetAligns(array('L','L','L'));
$pdf->RowNoLines(array('','Dengan ini mengajukan permohonan untuk mengikuti seleksi penerimaan mahasiswa baru Program Penelusuran Minat dan Prestasi (PMDP) Politeknik Kesehatan Semarang Tahun Akademik 2017/2018 dengan pilihan:',''));

$pdf->SetWidths(array(5,60,5,125));
$pdf->RowNoLines(array('','Program Studi',':','Prodi D III Analis Kesehatan Semarang'));
$pdf->RowNoLines(array('','Kode Program Studi',':','71'));

$pdf->SetFont('Arial', 'I', 8);
$pdf->Cell(130, 67, '', 0, 1, 'L');
$pdf->Cell(5);
$pdf->Cell(125, 7, 'DIKIRIM KE PANITIA (Hal 1 dari 2 Formulir Rekomendasi Kepala Sekolah)', 0, 1, 'L');


//Halaman 3
$pdf->AddPage();
// Arial bold 15
$pdf->SetFont('Arial', 'BU', 14);
// Title
$pdf->Rect(5, 5, 200, 275, 'D');
$pdf->Cell(200, 12, 'REKAPITULASI NILAI RAPOR', 0, 1, 'C');

$pdf->SetFont('Arial', '',11);
$pdf->Cell(5);
$pdf->Cell(10, 7, '', 'LT', 0, 'C');
$pdf->Cell(40, 7, '', 'LT', 0, 'C');
$pdf->Cell(120,7, 'Nilai', 1, 0, 'C');
$pdf->Cell(20, 7, '', 'RT', 1, 'C');

$pdf->Cell(5);
$pdf->Cell(10, 7, 'No', 'L',0,'C');
$pdf->Cell(40, 7, 'Mata Pelajaran', 'L', 0, 'C');
$pdf->Cell(40, 7, 'Kelas X', 1, 0, 'C');
$pdf->Cell(40, 7, 'Kelas XI', 1, 0, 'C');
$pdf->Cell(40, 7, 'Kelas XII', 1, 0, 'C');
$pdf->Cell(20, 7, 'Rata-rata', 'R', 1, 'C');

$pdf->Cell(5);
$pdf->Cell(10, 7, '', 'L');
$pdf->Cell(40, 7, '', 'L', 0, 'C');
$pdf->Cell(20, 7, 'Smt 1', 1, 0, 'C');
$pdf->Cell(20, 7, 'Smt 2', 1, 0, 'C');
$pdf->Cell(20, 7, 'Smt 1', 1, 0, 'C');
$pdf->Cell(20, 7, 'Smt 2', 1, 0, 'C');
$pdf->Cell(20, 7, 'Smt 1', 1, 0, 'C');
$pdf->Cell(20, 7, 'Smt 2', 1, 0, 'C');
$pdf->Cell(20, 7, '', 'R', 1, 'C');

$pdf->SetWidths(array(10,40,20,20,20,20,20,20,20));
$pdf->SetAligns(array('C','L','R','R','R','R','R','R','R'));
$pdf->Cell(5);
$pdf->Row(array('1','Matematika','90.00','90.00','90.00','90.00','90.00','90.00','90.00'));
$pdf->Cell(5);
$pdf->Row(array('1','Bahasa Indonesia','90.00','90.00','90.00','90.00','90.00','90.00','90.00'));
$pdf->Cell(5);
$pdf->Row(array('1','Fisika','90.00','90.00','90.00','90.00','90.00','90.00','90.00'));
$pdf->Cell(5);
$pdf->Row(array('1','xxx','90.00','90.00','90.00','90.00','90.00','90.00','90.00'));

$pdf->Cell(5, 7, '', 0, 1);
$pdf->SetFont('Arial', 'BU', 14);
$pdf->Cell(200, 12, 'PRESTASI PENDUKUNG *)', 0, 1, 'C');

$pdf->SetFont('Arial', '',11);
$pdf->SetWidths(array(10,90,90));
$pdf->SetAligns(array('C','C','C'));
$pdf->Cell(5);
$pdf->Row(array('No','Nama Prestasi Juara Lomba / Kompetensi Iptek, Seni dan Olahraga','Prestasi / Tingkat'));
$pdf->SetAligns(array('C','L','L'));
$pdf->Cell(5);
$pdf->Row(array('1','Juara Makan','Tingkat Internasional '));

$pdf->Cell(5, 7, '', 0, 1);
$pdf->Cell(5);
$pdf->Cell(190, 12, '*) Keterangan', 0, 1, 'L');

$pdf->SetWidths(array(5,10,35,10,130));
$pdf->SetAligns(array('L','L','L','C','L'));
$pdf->RowNoLines(array('','1. ','Nama Lomba',':','diisi nama kegiatan yang diikuti'));
$pdf->RowNoLines(array('','2. ','Prestasi / Tingkat',':','diisi prestasi yang diperoleh pada kegiatan tersebut minimal kegiatan tersebut dilaksanakan tingkat Kabupaten/Kota.'));

$pdf->Cell(5, 7, '', 0, 1);
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, 'Semarang, 20 Januari 2017', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, 'Kepala Sekolah SMAN 1', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, 'JUANDA', 0, 1, 'C');

$pdf->SetFont('Arial', 'I', 8);
$pdf->Cell(125, 57, '', 0, 1, 'L');
$pdf->Cell(5);
$pdf->Cell(125, 7, 'DIKIRIM KE PANITIA (Hal 2 dari 2 Formulir Rekomendasi Kepala Sekolah)', 0, 1, 'L');

//Halaman 4
$pdf->AddPage();
// Arial bold 15
$pdf->SetFont('Arial', 'B', 14);
// Title
$pdf->Rect(5, 5, 200, 275, 'D');
$pdf->Cell(200, 12, 'SURAT PERSETUJUAN ORANG TUA / WALI', 0, 1, 'C');

$pdf->SetFont('Arial', '',11);
$pdf->Cell(5);
$pdf->Cell(190, 7, 'Yang bertandatangan di bawah ini:', 0, 1, 'L');
$pdf->SetWidths(array(5,55,5,125));
$pdf->SetAligns(array('L','L','C','L'));
$pdf->RowNoLines(array('','Nama',':','........................................................................'));
$pdf->RowNoLines(array('','Tempat, Tanggal Lahir',':','........................................................................'));
$pdf->RowNoLines(array('','Alamat',':','........................................................................'));
$pdf->RowNoLines(array('','Nomor KTP',':','........................................................................'));
$pdf->RowNoLines(array('','Telephone',':','........................................................................'));

$pdf->SetWidths(array(5,190,5));
$pdf->SetAligns(array('L','L','L'));
$pdf->RowNoLines(array('','Orang Tua / Wali dari Peserta Seleksi Penerimaan Mahasiswa Baru Jalur PMDP Politeknik Kesehatan Semarang dengan data sebagai berikut:',''));

$pdf->SetWidths(array(5,55,5,125));
$pdf->SetAligns(array('L','L','C','L'));
$pdf->RowNoLines(array('','Nama',':','ALMAHYRA'));
$pdf->RowNoLines(array('','Tempat, Tanggal Lahir',':','BREBES / 20 Januari 2017'));
$pdf->RowNoLines(array('','Alamat',':','FSDFSD'));
$pdf->RowNoLines(array('','No Pendaftaran',':','PMDP710002'));
$pdf->RowNoLines(array('','Asal Sekolah',':','SMAN 1'));
$pdf->RowNoLines(array('','Telephone',':','0369264296'));

$pdf->Cell(5);
$pdf->Cell(190, 7, 'Dengan ini menyatakan dengan sesungguhnya bahwa saya: ', 0, 1, 'L');

$pdf->SetWidths(array(5,10,170,5));
$pdf->SetAligns(array('L','L','L','L'));
$pdf->RowNoLines(array('','1.','Saya mengetahui dan menyetujui yang bersangkutan mengikuti proses seleksi dan atau pendidikan sebagai mahasiswa di Politeknik Kesehatan Semarang.',''));
$pdf->RowNoLines(array('','2.','Benar yang bersangkutan menjadi tanggung jawab saya sepenuhnya selama masa pendidikan berlangsung di Politeknik Kesehatan Semarang.',''));

$pdf->Cell(5, 7, '', 0, 1);
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, 'Semarang, 20 Januari 2017', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, 'Yang membuat pernyataan,', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(105, 7, '', 0, 0, 'L');
$pdf->Cell(35, 7, 'Materai', 'LTR', 0, 'C');
$pdf->Cell(50, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(105, 7, '', 0, 0, 'L');
$pdf->Cell(35, 7, '6000', 'LBR', 0, 'C');
$pdf->Cell(50, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '........................................................', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, 'Orang Tua / Wali', 0, 1, 'C');


//Halaman 5
$pdf->AddPage();
$pdf->Rect(5, 5, 200, 275, 'D');

$pdf->SetFont('Arial', '',6);
$pdf->Image('./packages/tugumuda/portal/images/print/poltekkes-logo.png',11,9,13);
$pdf->Cell(5);
$pdf->Cell(15, 15, '', 'LT', 0, 'C');
$pdf->Cell(72, 2, '', 'TR', 1, 'C');
$pdf->Cell(5);
$pdf->Cell(15);
$pdf->Cell(72, 3, 'KEMENTERIAN KESEHATAN REPUBLIK INDONESIA', 'R', 1, 'C');
$pdf->Cell(5);
$pdf->Cell(15);
$pdf->Cell(72, 3, 'POLITEKNIK KESEHATAN KEMENKES SEMARANG', 'R', 1, 'C');
$pdf->Cell(5);
$pdf->Cell(15);
$pdf->Cell(72, 3, 'Jl.Tirto Agung Banyumanik-Semarang 50239 Telp./Fax : 024-7460274', 'R', 1, 'C');
$pdf->Cell(5);
$pdf->Cell(15);
$pdf->Cell(72, 4, 'www.poltekkes-smg.ac.id, Email : poltekkes-smg@poltekkes-smg.ac.id.', 'R', 1, 'C');

$pdf->SetFont('Arial', 'B',8);
$pdf->Cell(5);
$pdf->Cell(87, 4, 'KARTU PESERTA SELEKSI PENERIMAAN MAHASISWA BARU', 'TLR', 1, 'C');
$pdf->Cell(5);
$pdf->Cell(87, 4, 'JALUR PMDP', 'LBR', 1, 'C');

$pdf->Image('./packages/tugumuda/portal/images/print/iso-logo.png',170,8,32);
$pdf->Cell(200, 7, '', 0, 1);
$pdf->SetFont('Arial', '',11);
$pdf->SetWidths(array(5,55,5,125));
$pdf->SetAligns(array('L','L','C','L'));
$pdf->RowNoLines(array('','Nama',':','ALMAHYRA'));
$pdf->RowNoLines(array('','No Pendaftaran',':','PMDP710002'));
$pdf->RowNoLines(array('','Nama Sekolah',':','SMAN 1'));
$pdf->RowNoLines(array('','Jenis Kelamin',':','LAKI-LAKI'));
$pdf->RowNoLines(array('','Program Studi',':','Prodi D III Analis Kesehatan Semarang'));


$pdf->Cell(5, 7, '', 0, 1);
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, 'Semarang, 20 Januari 2017', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(40, 7, '', 'LRT', 0, 'L');
$pdf->Cell(85, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(40, 7, '', 'LR', 0, 'L');
$pdf->Cell(85, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(40, 7, 'Pas foto', 'LR', 0, 'C');
$pdf->Cell(85, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');

$pdf->Image('./packages/tugumuda/portal/images/print/stempel.jpeg',95,90,55);

$pdf->Cell(5);
$pdf->Cell(40, 7, '4x6', 'LR', 0, 'C');
$pdf->Cell(85, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(40, 7, '', 'LR', 0, 'L');
$pdf->Cell(85, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, 'ALMAHYRA', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(40, 7, '', 'LRB', 0, 'L');
$pdf->Cell(85, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '........................................................', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, 'Nama & Tanda Tangan Peserta', 0, 1, 'C');

$pdf->SetFont('Arial', 'I', 8);
$pdf->Cell(125, 7, '', 0, 1, 'L');
$pdf->Cell(5);
$pdf->Cell(125, 7, 'UNTUK PESERTA', 0, 1, 'L');

$pdf->Cell(5);
$pdf->Cell(190, 2, '', 'T', 1, 'L');

$pdf->SetFont('Arial', 'BU', 12);
$pdf->Cell(5);
$pdf->Cell(200, 7, 'MOHON DIPERHATIKAN', 0, 1, 'L');

$pdf->SetFont('Arial', '', 12);
$pdf->SetWidths(array(5,10,170,5));
$pdf->SetAligns(array('L','L','L','L'));
$pdf->RowNoLines(array('','a.','Kartu ini berlaku sebagai bukti pendaftaran Seleksi Penerimaan Mahasiswa Baru Jalur PMDP',''));
$pdf->RowNoLines(array('','b.','Kartu ini harus dibawa pada saat dinyatakan lulus nominasi Seleksi Tahap I dan akan mengikuti seleksi Tahap II',''));
$pdf->RowNoLines(array('','c.','Kartu ini harap disimpan baik-baik untuk keperluan Seleksi Tahap II (Test Kesehatan) dan Daftar Ulang (Registrasi)',''));
$pdf->RowNoLines(array('','d.','Batas waktu berkas diterima panitia paling lambat tanggal 14 Maret 2016',''));

//Halaman 6
$pdf->AddPage();
$pdf->Rect(5, 5, 200, 275, 'D');

$pdf->SetFont('Arial', '',6);
$pdf->Image('./packages/tugumuda/portal/images/print/poltekkes-logo.png',11,9,13);
$pdf->Cell(5);
$pdf->Cell(15, 15, '', 'LT', 0, 'C');
$pdf->Cell(72, 2, '', 'TR', 1, 'C');
$pdf->Cell(5);
$pdf->Cell(15);
$pdf->Cell(72, 3, 'KEMENTERIAN KESEHATAN REPUBLIK INDONESIA', 'R', 1, 'C');
$pdf->Cell(5);
$pdf->Cell(15);
$pdf->Cell(72, 3, 'POLITEKNIK KESEHATAN KEMENKES SEMARANG', 'R', 1, 'C');
$pdf->Cell(5);
$pdf->Cell(15);
$pdf->Cell(72, 3, 'Jl.Tirto Agung Banyumanik-Semarang 50239 Telp./Fax : 024-7460274', 'R', 1, 'C');
$pdf->Cell(5);
$pdf->Cell(15);
$pdf->Cell(72, 4, 'www.poltekkes-smg.ac.id, Email : poltekkes-smg@poltekkes-smg.ac.id.', 'R', 1, 'C');

$pdf->SetFont('Arial', 'B',8);
$pdf->Cell(5);
$pdf->Cell(87, 4, 'KARTU PESERTA SELEKSI PENERIMAAN MAHASISWA BARU', 'TLR', 1, 'C');
$pdf->Cell(5);
$pdf->Cell(87, 4, 'JALUR PMDP', 'LBR', 1, 'C');

$pdf->Image('./packages/tugumuda/portal/images/print/iso-logo.png',170,8,32);
$pdf->Cell(200, 7, '', 0, 1);
$pdf->SetFont('Arial', '',11);
$pdf->SetWidths(array(5,55,5,125));
$pdf->SetAligns(array('L','L','C','L'));
$pdf->RowNoLines(array('','Nama',':','ALMAHYRA'));
$pdf->RowNoLines(array('','No Pendaftaran',':','PMDP710002'));
$pdf->RowNoLines(array('','Nama Sekolah',':','SMAN 1'));
$pdf->RowNoLines(array('','Jenis Kelamin',':','LAKI-LAKI'));
$pdf->RowNoLines(array('','Program Studi',':','Prodi D III Analis Kesehatan Semarang'));


$pdf->Cell(5, 7, '', 0, 1);
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, 'Semarang, 20 Januari 2017', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(40, 7, '', 'LRT', 0, 'L');
$pdf->Cell(85, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(40, 7, '', 'LR', 0, 'L');
$pdf->Cell(85, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(40, 7, 'Pas foto', 'LR', 0, 'C');
$pdf->Cell(85, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');

$pdf->Cell(5);
$pdf->Cell(40, 7, '4x6', 'LR', 0, 'C');
$pdf->Cell(85, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(40, 7, '', 'LR', 0, 'L');
$pdf->Cell(85, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, 'ALMAHYRA', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(40, 7, '', 'LRB', 0, 'L');
$pdf->Cell(85, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '........................................................', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, 'Nama & Tanda Tangan Peserta', 0, 1, 'C');

$pdf->SetFont('Arial', 'I', 8);
$pdf->Cell(125, 7, '', 0, 1, 'L');
$pdf->Cell(5);
$pdf->Cell(125, 7, 'DIKIRIM KE PANITIA', 0, 1, 'L');


//Halaman 7
$pdf->AddPage();
$pdf->Rect(5, 5, 200, 275, 'D');

$pdf->Cell(100, 7, '', 0, 0);
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(95, 7, 'FM-POLTEKKES-SMG-BM-01-02/R0', 0, 1, 'R');

$pdf->SetFont('Arial', 'BU', 14);
$pdf->Cell(200, 12, 'SURAT PERNYATAAN', 0, 1, 'C');

$pdf->SetFont('Arial', '',11);
$pdf->Cell(5);
$pdf->Cell(190, 7, 'Yang bertandatangan di bawah ini:', 0, 1, 'L');

$pdf->SetWidths(array(5,55,5,125));
$pdf->SetAligns(array('L','L','C','L'));
$pdf->RowNoLines(array('','Nama',':','ALMAHYRA'));
$pdf->RowNoLines(array('','Tempat, Tanggal Lahir',':','BREBES / 20 Januari 2017'));
$pdf->RowNoLines(array('','Asal Sekolah',':','SMAN 1'));
$pdf->RowNoLines(array('','Alamat',':','FSDFSD'));
$pdf->RowNoLines(array('','Telephone',':','0369264296'));

$pdf->Cell(5);
$pdf->Cell(190, 7, 'Dengan ini menyatakan dengan sesungguhnya bahwa saya: ', 0, 1, 'L');

$pdf->SetWidths(array(5,10,170,5));
$pdf->SetAligns(array('L','L','L','L'));
$pdf->RowNoLines(array('','1.','Bersungguh-sungguh berminat mengikuti pendidikan Program Studi Prodi D III Analis Kesehatan Semarang Politeknik Kesehatan Semarang',''));
$pdf->RowNoLines(array('','2.','Apabila diterima sebagai mahasiswa baru tidak akan mengajukan pindah ke Jurusan/Prodi lain di lingkungan Politeknik Kesehatan Semarang',''));
$pdf->RowNoLines(array('','2.','Dinyatakan gugur bila tidak lulus dari Satuan Pendidikan (SMA/MA)',''));
$pdf->RowNoLines(array('','2.','Akan mentaati semua peraturan dan tata tertib yang berlaku di Politeknik Kesehatan Semarang',''));

$pdf->Cell(5);
$pdf->Cell(190, 7, 'Demikian pernyataan ini saya buat dengan sebenarnya untuk dapat dipergunakan sebagaimana mestinya.', 0, 1, 'L');

$pdf->Cell(5, 7, '', 0, 1);
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, 'Semarang, 20 Januari 2017', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, 'Yang membuat pernyataan,', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(105, 7, '', 0, 0, 'L');
$pdf->Cell(35, 7, 'Materai', 'LTR', 0, 'C');
$pdf->Cell(50, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(105, 7, '', 0, 0, 'L');
$pdf->Cell(35, 7, '6000', 'LBR', 0, 'C');
$pdf->Cell(50, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, '', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, 'ALMAHYRA', 0, 1, 'C');
$pdf->Cell(5);
$pdf->Cell(125, 7, '', 0, 0, 'L');
$pdf->Cell(65, 7, 'Nama & Tanda Tangan Peserta', 0, 1, 'C');

$pdf->SetFont('Arial', 'I', 8);
$pdf->Cell(125, 7, '', 0, 1, 'L');
$pdf->Cell(5);
$pdf->Cell(125, 7, 'DIKIRIM KE PANITIA', 0, 1, 'L');


//Halaman 8
$pdf->AddPage();
$pdf->Rect(30, 15, 150, 50, 'D');
$pdf->SetFont('Arial', 'B', 12);

$pdf->Cell(190, 17, '', 0, 1, 'L');
$pdf->SetWidths(array(25,150,25));
$pdf->SetAligns(array('L','C','L'));
$pdf->RowNoLines(array('','Kepada Yth: Direktur Politeknik Kesehatan Semarang
UP. Panitia SIPENMARU Jalur PMDP Tahun 2017
d/a Jalan Tirto Agung, Pedalangan, Banyumanik, Semarang',''));

$pdf->Cell(190, 14, '', 0, 1, 'L');

$pdf->Rect(30, 75, 150, 50, 'D');
$pdf->SetFont('Arial', 'B', 12);

$pdf->Cell(190, 23, '', 0, 1, 'L');
$pdf->SetWidths(array(25,150,25));
$pdf->SetAligns(array('L','C','L'));
$pdf->RowNoLines(array('','Pengirim:
ALMAHYRA
FSDFSD',''));


$pdf->Output('Kartu Seleksi Penerimaan Mahasiswa Baru Jalur PMDP', 'I');
?>